# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d841359de95cadc7db651494c29100a1aafc7381a0ee95c5f2c92c5a45e5131e9e94496c666044942ad0da8c27c797ebd60aac7213bd146103b0ea551a79868

test:
  secret_key_base: 4cb53f56332c93cb46786816a9750c0189897f0b73c639ce6d425e4f5ae7df1aad21dc2d8106a2e031ccc5d458df3e325d53e31c62d5803b35f4804314ad6c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
